name: Ruby

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  ruby-versions:
    if: ${{ startsWith(github.repository, 'ruby/') || github.event_name != 'schedule' }}
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      engine: cruby-jruby
      min_version: 3.3

  build:
    needs: ruby-versions
    name: CI (${{ matrix.ruby }} / ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ruby: ${{ fromJson(needs.ruby-versions.outputs.versions) }}
        os: [ ubuntu-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
